const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),babel=require('@babel/core');
function load(file,mocks){const {code}=babel.transformSync(fs.readFileSync(file,'utf8'),{configFile:false,babelrc:false,plugins:[require.resolve('@babel/plugin-transform-modules-commonjs')]});const mod={exports:{}};new Function('require','module','exports',code)(name=>mocks[name],mod,mod.exports);return mod.exports;}
const memory=()=>{const data=new Map();return {data,getItem:async k=>data.get(k)||null,setItem:async(k,v)=>data.set(k,v),removeItem:async k=>data.delete(k)};};
const storage=memory();
const cache=load('src/shared/offline/profileCache.js',{'@react-native-async-storage/async-storage':storage});
test('offline cache excludes personal data and credentials',()=>{const record=cache.cacheRecord('a',{role:'shop',verificationStatus:'approved',email:'private',phone:'private',password:'secret',shop:{shopName:'Demo',address:'private'}});assert.deepEqual(record.profile,{role:'shop',verificationStatus:'approved',shop:{shopName:'Demo'}});});
test('offline cache refuses admin, pending and rejected shops',()=>{for(const profile of [{role:'admin'},{role:'shop',verificationStatus:'pending'},{role:'shop',verificationStatus:'rejected'}])assert.equal(cache.cacheRecord('a',profile),null);});
test('offline cache rejects expired, future, foreign-account, corrupt and old-schema entries',()=>{const record=cache.cacheRecord('a',{role:'owner'},1000);for(const [raw,uid,now] of [[JSON.stringify(record),'b',1000],[JSON.stringify(record),'a',1000+cache.CACHE_AGE+1],[JSON.stringify(record),'a',999],['broken','a',1000],[JSON.stringify({...record,version:0}),'a',1000]])assert.equal(cache.parseCache(raw,uid,now),null);});
test('cache is user-isolated and cleared on sign-out',async()=>{await cache.saveProfileCache('a',{role:'owner'});assert.ok(await cache.readProfileCache('a'));assert.equal(await cache.readProfileCache('b'),null);await cache.clearProfileCache('a');assert.equal(await cache.readProfileCache('a'),null);});
function secure(){const memoryStore=memory();const store={getItemAsync:memoryStore.getItem,setItemAsync:memoryStore.setItem,deleteItemAsync:memoryStore.removeItem};const legacy=memory();const {createSecurePersistence}=load('src/shared/services/securePersistence.js',{'expo-secure-store':store,'@react-native-async-storage/async-storage':legacy});return {store,data:memoryStore.data,legacy,adapter:createSecurePersistence(store,legacy)};}
test('encrypted persistence handles large Unicode payloads and removes plaintext legacy sessions',async()=>{const s=secure(),key='firebase:authUser:key:[DEFAULT]',value='車🚙'.repeat(2200);await s.legacy.setItem(key,'old-token');assert.equal(await s.adapter.getItem(key),null);assert.equal(await s.legacy.getItem(key),null);await s.adapter.setItem(key,value);assert.equal(await s.adapter.getItem(key),value);for(const [k,v] of s.data){assert.match(k,/^[a-zA-Z0-9._-]+$/);assert.ok(Buffer.byteLength(v,'utf8')<2048);}await s.adapter.removeItem(key);assert.equal(s.data.size,0);});
test('failed secure write preserves the prior complete session',async()=>{const s=secure();await s.adapter.setItem('session','old');const original=s.store.setItemAsync;s.store.setItemAsync=async(k,v)=>{if(k.endsWith('.1'))throw Error('full');return original(k,v);};await assert.rejects(()=>s.adapter.setItem('session','x'.repeat(1000)),/full/);assert.equal(await s.adapter.getItem('session'),'old');});
test('serialized secure writes cannot interleave session chunks',async()=>{const s=secure();await Promise.all([s.adapter.setItem('session','a'.repeat(4000)),s.adapter.setItem('session','b'.repeat(5000))]);assert.equal(await s.adapter.getItem('session'),'b'.repeat(5000));});
