const {test,before,after,beforeEach}=require('node:test');
const fs=require('node:fs');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,setDoc,getDoc,updateDoc,serverTimestamp,collection,getDocs}=require('firebase/firestore');
const {ref,uploadBytes,getBytes}=require('firebase/storage');
let env;
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-pmr-security',firestore:{rules:fs.readFileSync('firestore.rules','utf8')},storage:{rules:fs.readFileSync('storage.rules','utf8')}});});
after(async()=>{await env?.cleanup();});
beforeEach(async()=>{await env.clearFirestore();await env.clearStorage();});
const context=(uid,verified=true,admin=false)=>env.authenticatedContext(uid,{email:uid+'@example.com',email_verified:verified,admin});
const shop={shopName:'Demo Shop',regNumber:'123',address:'1 Demo Road',city:'Johannesburg',province:'Gauteng',services:'Paint'};
const profile=(uid,role='owner')=>({fullName:'Demo',email:uid+'@example.com',phone:'0821234567',role,createdAt:serverTimestamp(),termsVersion:'academic-v1',termsAcceptedAt:serverTimestamp(),...(role==='shop'?{shop,verificationStatus:'pending'}:{})});
const meta=(uid,kind)=>({path:`verification/${uid}/${kind}`,name:'sample.pdf',size:4,contentType:'application/pdf',uploadedAt:serverTimestamp()});
async function seed(uid,role='shop',status='pending'){await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'users',uid),{...profile(uid,role),...(role==='shop'?{verificationStatus:status}:{})});});}
test('unverified owner and shop may create only their own onboarding profile',async()=>{for(const role of ['owner','shop']){const uid=role;await assertSucceeds(setDoc(doc(context(uid,false).firestore(),'users',uid),profile(uid,role)));}await assertFails(setDoc(doc(context('attacker').firestore(),'users','victim'),profile('attacker')));});
test('anonymous users cannot read profiles',async()=>{await seed('owner','owner');await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'users','owner')));});
test('clients cannot self-register as admin, add privilege fields or preapprove shops',async()=>{const db=context('u').firestore();for(const data of [profile('u','admin'),{...profile('u'),admin:true},{...profile('u','shop'),verificationStatus:'approved'}])await assertFails(setDoc(doc(db,'users','u'),data));});
test('roles cannot be edited and shops cannot approve themselves',async()=>{await seed('u');const d=doc(context('u').firestore(),'users','u');await assertFails(updateDoc(d,{role:'admin'}));await assertFails(updateDoc(d,{verificationStatus:'approved'}));});
test('customer cannot read another account or list users',async()=>{await seed('other','owner');const db=context('u').firestore();await assertFails(getDoc(doc(db,'users','other')));await assertFails(getDocs(collection(db,'users')));});
test('admin profile or unverified admin claim alone does not grant access',async()=>{await seed('admin','admin');await seed('other','owner');await assertFails(getDoc(doc(context('admin',true,false).firestore(),'users','other')));await assertFails(getDoc(doc(context('admin',false,true).firestore(),'users','other')));await assertSucceeds(getDoc(doc(context('admin',true,true).firestore(),'users','other')));});
test('malformed shop fields and extra nested keys are denied',async()=>{const db=context('u').firestore();for(const details of [{...shop,services:[]},{...shop,city:''},{...shop,admin:true}])await assertFails(setDoc(doc(db,'users','u'),{...profile('u','shop'),shop:details}));});
test('unverified shops cannot write document metadata',async()=>{await seed('u');await assertFails(setDoc(doc(context('u',false).firestore(),'users','u','documents','ownerId'),meta('u','ownerId')));});
test('verified pending shop can upload metadata only within its own document paths',async()=>{await seed('u');const db=context('u').firestore();await assertSucceeds(setDoc(doc(db,'users','u','documents','ownerId'),meta('u','ownerId')));for(const value of [{...meta('u','ownerId'),path:'verification/other/ownerId'},{...meta('u','ownerId'),size:0},{...meta('u','ownerId'),size:2.5},{...meta('u','ownerId'),contentType:'text/html'}])await assertFails(setDoc(doc(db,'users','u','documents','ownerId'),value));});
test('admin approval requires all three document records and cannot alter other fields',async()=>{await seed('u');await seed('admin','admin');const adminDb=context('admin',true,true).firestore();await assertFails(updateDoc(doc(adminDb,'users','u'),{verificationStatus:'approved'}));const db=context('u').firestore();for(const key of ['cipcCert','proofOfAddress','ownerId'])await setDoc(doc(db,'users','u','documents',key),meta('u',key));await assertSucceeds(updateDoc(doc(adminDb,'users','u'),{verificationStatus:'approved'}));await assertFails(updateDoc(doc(adminDb,'users','u'),{fullName:'changed'}));await assertFails(setDoc(doc(db,'users','u','documents','ownerId'),meta('u','ownerId')));});
test('Storage denies unverified, foreign-owner, non-shop, invalid type and oversized uploads',async()=>{await seed('u');await seed('customer','owner');const upload=(c,path='verification/u/ownerId',type='application/pdf',size=4)=>uploadBytes(ref(c.storage(),path),new Uint8Array(size),{contentType:type});await assertFails(upload(context('u',false)));await assertFails(upload(context('other')));await assertFails(upload(context('customer'),'verification/customer/ownerId'));await assertFails(upload(context('u'),undefined,'text/html'));await assertFails(upload(context('u'),undefined,'application/pdf',5242881));await assertSucceeds(upload(context('u')));});
test('private shop documents can only be read by their verified owner or verified claimed admin',async()=>{await seed('u');await seed('admin','admin');await uploadBytes(ref(context('u').storage(),'verification/u/ownerId'),new Uint8Array(4),{contentType:'application/pdf'});const read=c=>getBytes(ref(c.storage(),'verification/u/ownerId'));await assertFails(read(env.unauthenticatedContext()));await assertFails(read(context('other')));await assertFails(read(context('u',false)));await assertSucceeds(read(context('u')));await assertSucceeds(read(context('admin',true,true)));});
test('unimplemented collections remain denied',async()=>{await assertFails(setDoc(doc(context('u').firestore(),'bookings','one'),{owner:'u'}));});

test('admin claim without an admin profile cannot read other accounts',async()=>{await seed('owner','owner');await assertFails(getDoc(doc(context('unprovisioned',true,true).firestore(),'users','owner')));});
